### ISSUE TITLE
Video-Freeze on Android 11

### ISSUE THREAD

**Issue by NathanielDemerest** [Collabsvito/REpo-AiO#1]
The streams take a long time to load (if at all) and then abort after a few seconds, with the result that the screen goes black and Kodi freezes.

One can then only press the home button to force quit the app.

**Comment by Collabsvito** [comment]
@NathanielDemerest 
Hallo Nathaniel,
Du darfst hier auch gerne deutsch mit mir sprechen !
Sorry für die späte Rückmeldung, aber die Gesundheit hat ihren Tribut gefordert.
Würdest Du mir bitte noch sagen bei welchem meiner Addons der Fehler auftritt, damit ich diesen reproduzieren kann.
MfG

**Comment by NathanielDemerest** [comment]
Ok also dann. Der Fehler tritt vermutlich bei allen Videos im Myspass Addon auf. Das ist das einzige Addon, was ich aus dieser Repo verwende. 

Getestet habe ich es mit mehreren Videos. Aber speziell zum Beispiel mit den Stromberg Staffeln.

Entweder der Ladekreis rödelt ewig vor sich hin und/oder das Video friert nach kurzer Zeit ein. Danach wird der Bildschirm schwarz und man kann dann nur die Home-Taste drücken, um Kodi danach zwangsweise zu beenden und wieder starten zu können.

Nur unter Android 11 tritt das Problem auf. Unter Android 9 und 10 funktionieren die Streams im Myspass Addon einwandfrei.

**Comment by Collabsvito** [comment]
Da Du ja als Fachmann für Android bekannt bist, werde ich Dir bestimmt keine neuen Erkenntnisse liefern können, indem ich Dir sage dass es sich in diesem Fall um einen Fehler des Kodi-Players handelt !

Die Videos der Stromberg Staffeln bestehen alle aus Einzel-Videos (mp4) und nicht wie viele andere Serien aus mind. 2 Teilen (Playlisten) und werden direkt über Kodi ohne INPUTSTREAM.ADAPTIVE wiedergegeben.
Sobald das Video an den Kodi-Player übergeben worden ist, ist es ein Kodi-internes-Problem und nicht mehr Sache des MySpass-Addons.
Ich kann nur vermuten, dass Kodi in diesem Fall Probleme mit der Wiedergabe von MP4-Videos hat und würde Dir raten Dies mit anderen MP4 Quellen gegen zu testen.
Im kodi.log müsste kurz vor dem Start des Players solch eine Meldung auftauchen (ohne debug): NOTICE: [plugin.video.myspass_de v.4.1.3+matrix.1](navigator.playCODE) StreamURL : https://cldf-od.r53.cdn.tv1.eu/secdl/ff9ae17dc209afdc52e64bb911a9fc32/625ca0cf/11021brainpool/ondemand/3583brainpool/163840/myspass2009/12/27/2330/815/815_61.mp4 - danach beginnt die Interaktion von KODI.
Schade, dass ich in diesem Fall nicht mehr Hilfe leisten kann.
MfG

**Comment by NathanielDemerest** [comment]
Mit anderen MP4-Dateien (von meinem NAS) habe ich keine Probleme unter Kodi. Es liegt wohl nicht am Player in Kodi, sonst hätte es unter Android 9 (vor dem neuen Shield Experience Upgrade) schon Probleme gegeben. Ich tippe immer noch auf die Lese-/Schreibbeschränkung von Android 11 auf den Android/data Ordner in Kodi. Irgendwas wird in diesen Ordner geschrieben oder ausgelesen, was dank der Zugriffsbeschränkungen seit Android 11 zu Problemen bei Myspass führt.

Unter Android 11 selbst habe ich ja kurz nach dem Upgrade den Lese-/Schreibzugriff auf den Android/data Ordner wieder hergestellt. 

Kodi verwendet eine andere Schnittstelle in seinem Dateimanager. Daher hatte ich mal eine Build von Maven so modifiziert, dass theoretisch der Speicherzugriff auf das Android/data Verzeichnis wieder möglich wird. Doch Android 11 stellt sich immer noch quer und verweigert weiterhin den Zugriff. 

Nvidia wollte sich ja mit Google austauschen, um solche Probleme zu beheben. 

Ich bin immer noch am Testen, wie ich das umgehen kann, damit es wieder läuft. Alternativ könnte ich sonst nur einen externen Player für derartige Streams in Kodi einbinden über die playercorefactory.xml oder weiterhin die Myspass Videos über meinen Fire TV Stick 4K Max mit Android 9 wiedergeben.

**Comment by Collabsvito** [comment]
Okay dann verstehe ich die Probleme.
Denn ich lasse im DATA-Ordner des Addons eine Json-Datei anlegen, um die Wiedergabepunkte für Einzelvideos zwischenzuspeichern (gesehen Markierung mit Zugriff durch unterschiedliche Ordner) und ich wüsste da keine andere Möglichkeit um dies umzusetzen.
Wenn Android den Zugriff verweigert kannst Du ja gar keine "settings" bei irgendeinem Addon festlegen, das macht KODI dann ja ungenießbar !

Wenn Dir die gesehen-Markierungen nicht so wichtig sind, könnte ich Dir eine Version fertigstellen ohne diese Json-Datei !
_Falls "JA" bitte ich um kurze Mitteilung hier !_

**Comment by NathanielDemerest** [comment]
Ja, zumindest mal zum Testen, ob an meiner Theorie was dran ist oder ob es sich um eine andere Beschränkung handelt, die ich aber bis jetzt noch nicht auf dem Schirm habe. Zudem teste ich nach jedem HotFix das Addon neu.

**Comment by Collabsvito** [comment]
OKAY, here we are.
Eine spezielle Version für Dich ohne anlegen der Json-Datei im Data-Ordner !
Diese Version hat einen anderen Pfad im Kodiverzeichnis und einen anderen Namen, um ein Überschreiben und Verwechselungen auszuschließen.
[plugin.video.myspass_eleven-2022.04.28+matrix.1.zip](https://github.com/Collabsvito/REpo-AiO/files/8585670/plugin.video.myspass_eleven-2022.04.28%2Bmatrix.1.zip)
Viel Erfolg :smiley:

**Comment by NathanielDemerest** [comment]
Ok und Danke vorab für die Mühe. Ich teste es im Laufe des Abends mal und berichte dann hier wieder.

**Comment by NathanielDemerest** [comment]
Ach leider hat das auch nicht geholfen. Naja, einen Versuch war es wert. Hätte ja auch klappen können. Jetzt kann ich bloß noch auf die Updates bei Nvidia hoffen, was auch immer dafür verantwortlich ist, dass ausgerechnet dieses Myspass Addon unter Android 11 nicht richtig funktioniert.

Ich hatte ja ein kodi.log bei Kodinerds gepostet gehabt, aus dem vermutlich auch nicht mehr ersichtlich war, als das der Player ein Problem hat, den Content wiederzugeben.

Ich nutze unter Kodi erstmal weiterhin einen externen Player für das Myspass Addon und beobachte weiter, ob sich das Verhalten mit irgendeinem Update auch wieder mal ändert.

**Comment by Collabsvito** [comment]
Schade, aber in diesem Fall bin ich dann auch mit meinem Latein am Ende.
Da bei dieser Sonderedtion während der Nutzung wirklich kein Zugriff auf den Data-Ordner erfolgt und die Abspielfunktion direkt auf die Funktion "playVideo" verweist und dann das Einzelvideo als "xbmcplugin.setResolvedUrl" gesetzt wird mehr nicht !
Danke für das Feedback.

**Comment by NathanielDemerest** [comment]
Leider ist die Shield das einzige Gerät mit Android 11 bei mir. Von daher habe ich noch nicht viel Erfahrung mit der 11er Version. Und Experimente will ich mit der nicht wagen, bis ich ein weiteres Gerät mit der 11er Version habe. Ich muss wie bereits erwähnt, die Folgeupdates des Systems im Auge behalten und weiter testen.

Dennoch Danke für Deine Bemühungen.
