### ISSUE TITLE
Romanian language

### ISSUE THREAD

**Issue by freegigi** [Collabsvito/REpo-AiO#2]
Hi,

I hope English is fine, as I don't speak German.
It would be great if you could please add Romanian language, too? Yours is the only Euronews add-on that actually works.

![image](https://user-images.githubusercontent.com/6600835/187000804-843d2c0e-e465-4b45-b9c2-84e55c7e102d.png)

Thank you!

**Comment by Collabsvito** [comment]
@freegigi 
Sorry for the very late reply, but unfortunately I am very rarely online on Github.

The addon is based on the API of 'euronews' similar to the 'Android APP'.
I.e. all pages of 'euronews' which do not end with 'euronews.com' in the header unfortunately do not work !

Therefore a realization of your wish is unfortunately not possible.:weary:

Greetings
