### ISSUE TITLE
Feature Request plugin.video.rtlgroup.de: Premium Inhalte ausblenden

### ISSUE THREAD

**Issue by cpy82** [Collabsvito/REpo-AiO#5]
Hallo!
zunächst vielen Dank für dieses super Addon und die damit verbundene Arbeit!

Ich hätte eine Frage/Feature Request zum RTLPLUS - V.3 Addon: 
Wäre es möglich eine Option zu implementieren Premium Inhalte bei Bedarf auszublenden?
Hintergrund: Wenn man nur Free User ist und sich einfach inspirieren lassen möchte, was man z.B. an Dokumentationen noch schauen könnte, ggf. durch die Sendungen A-Z durchgeht, muss man an allen Premium Inhalten vorbei. Da wäre es klasse, wenn man bei Bedarf nur noch die Free User-Inhalte einblenden könnte.

Vielen Dank!

**Comment by Collabsvito** [comment]
**@cpy82** 

Auftrag ausgeführt, das gewünschte **Feature** ist jetzt in dem Addon "RTLPLUS - V.3 - v.1.1.5+matrix.1" enthalten !
Zu finden in den Einstellungen von "**RTLPLUS - V.3**" unter "**Fortgeschritten**", wichtig bitte auch die Hinweise (Helptexts) unter dieser Einstellung beachten !

Viel Spass damit, MFG

**Comment by Collabsvito** [comment]
@cpy82 

Genau da liegt das Problem die API kann nur bei Serien und Episoden filtern, für die anderen Funktionen gibt es leider keine Filter.
Deshalb gibt es dann bei einigen Staffeln beim anklicken nur leere Ordner (daher der Hinweis). 

Bei Serien wird mit "hasFreeEpisodes" und bei Episoden mit "payed" und "free" gefiltert, mehr Möglichkeiten sind vom Anbieter nicht vorgesehen.
Diese Unzulänglichkeit war für mich auch hauptsächlich der Grund weshalb ich diese Funktion bisher nicht ins Addon integriert habe (ich bin meist auch nur als FreeUser bei RTL+ unterwegs).

Ich hoffe jedenfalls, dass die API.v.3 (das "tvnow.de"-Addon arbeitet mit der aktuelleren API.v.1) noch lange arbeitet, da diese erheblich mehr Metadaten zu den Sendungen liefert als die API.v.1.

In diesem Sinne viel Freude damit.😉
