### ISSUE TITLE
plugin.video.euronews_com v.2.2.8+matrix.1: this live stream recording is not available

### ISSUE THREAD

**Issue by PanaqueH** [Collabsvito/REpo-AiO#6]
Euronews livestreaming doesn't work.

Detailed debug logging can be found here: https://paste.kodi.tv/yegiminuva

Thanks in advance for your support.

**Comment by Collabsvito** [comment]
@PanaqueH 

Talált hiba: nem az Euronews-Addon, hanem a Youtube-Addon !
Ez a kiadott hiba: "plugin.youtube.youtube_exceptions.YoutubeException: Ez a tartalom nem áll rendelkezésre ebben az alkalmazásban."
Csatolok egy ".zip" fájlt a Youtube addon béta tárolójához.
Kérlek telepítsd ezt a REPO-t a Kodi-dra, majd töltsd le+installáld a "plugin.video.youtube .v.7.0.2~alpha7".
Ennek ki kell javítania a hibát, kérjük, küldjön nekem egy rövid visszajelzést.😉

Tisztelettel
                                                                                                                                                                              Fordította: DeepL

[repository.yt.testing_unofficial-2.0.5.zip](https://github.com/Collabsvito/REpo-AiO/files/12105184/repository.yt.testing_unofficial-2.0.5.zip)

**Comment by PanaqueH** [comment]
Hi Collabsvito,

You are right, I did what you asked and now the livestream is working.

Thank you so much for your help.

Best Regards,
PanaqueH
