### ISSUE TITLE
Problems in RTL Plus Addon

### ISSUE THREAD

**Issue by maxbambi** [Collabsvito/REpo-AiO#7]
I have a free rtl plus account (no premium).

https://plus.rtl.de/video-tv/serien/alles-was-zaehlt-146430/2023-10-982471/episode-4298-justus-und-maximilian-wurden-in-die-irre-gefuehrt-927591 is a free video and i can play it from browser, but addon doesn't play it, like premium.

**Comment by harmony2302** [comment]
Same issue here with my premium account and Raspi4 (Kodi Matrix)- no streams avaiable, because RTL have changed the website & stream URL: https://www.kodinerds.net/thread/57646-release-tvnow-rtl-watchbox-vox-ntv-nowus-rtl2-nitro/?pageNo=120

Thx 4 checking & i hope solving

**Comment by jangrewe** [comment]
Can confirm issue with Premium subscription.

**Comment by smbon** [comment]
For me there is a similar problem. When I want to watch a free video it says "Video - Error!!! Es ist ein Fehler aufgetreten, bitte *Log* einsehen!!!"
In the Log it says:
error <general>: [plugin.video.rtlgroup.de v.1.1.6+matrix.1](navigator.getVideo)ERROR - ERROR - ERROR: ##### url: https://bff.apigw.tvnow.de/player/1674685 === error : {"status":404,"message":"Route not Found","routeExists":false} #####

If i open the Link (https://bff.apigw.tvnow.de/player/1674685) in my browser the exact same message appears, so it seems that the've changed the API.

**Comment by Collabsvito** [comment]
@All

Die genannten Probleme dürften inzwischen mit dem "plugin.video.rtlgroup.de .v.1.1.9" behoben sein (Die zuvor von mir genutzt API.v.1 wurde vom Provider abgeschaltet).

Falls nicht bitte nochmal melden.

Gruß
